FROM python:3.10-slim

WORKDIR /app

RUN apt update && apt-get install -y curl nano

RUN pip install --no-cache-dir \
    mlflow==2.6.0 \
    boto3 \
    psycopg2-binary \
    scikit-learn

COPY ./demo.py .
# COPY ./script.sh .