channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.3
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.24.4
  - psutil==5.9.5
  - scikit-learn==1.3.1
  - scipy==1.11.3
name: mlflow-env
